### ISSUE TITLE
Crashes server

### ISSUE THREAD

**Issue by timbersquirrel** [ThunderDoesPlugins/SimpleHomes#1]
This plugin doesn’t work please try to fix

**Comment by InspectorGadget** [comment]
No errors?

**Comment by Thunder33345** [comment]
yes please do provide errors so i can fix it
ideally how to reproduce it

**Comment by SuperOP535** [comment]
Did u update it to alpha9

**Comment by timbersquirrel** [comment]
It doesn’t give me and crashdump but I compiled the plugin to a phar using pmt.mcpe.fun then I dropped it in my plugins folder and it crashed my server

**Comment by Thunder33345** [comment]
give server logs then?

**Comment by timbersquirrel** [comment]
i am trash at trying to find errors in plugin please test to see if it works cuz i cant

**Comment by Thunder33345** [comment]
just screenshot your console, or upload your text on the console

**Comment by timbersquirrel** [comment]
?

**Comment by Thunder33345** [comment]
if you cant provide useful information i afraid i cannot help you
closing this for now unless you can provide more information

**Comment by timbersquirrel** [comment]
there are no errors that show -_-

**Comment by Thunder33345** [comment]
i cant fix it without errors
you can delete and start the server again then send me your server.log
sorry but i cant really help you if i dont know what has gone wrong

**Comment by timbersquirrel** [comment]
i will try to see if i can find it

**Comment by timbersquirrel** [comment]
ah here it is

**Comment by timbersquirrel** [comment]
===BEGIN CRASH DUMP===
eNrVW41v27iS/1cI5+FeW1jydxJ7L3dI03Tbt8nW16TXB6wXAS3Rtjb6qkjFcR/2f7+ZISlRittm
+9oCt0C2FkUO53t+Q0n/6qgoEZ3ZYNKf9ieHo+G02xFFkRWd2b86apfDrc75zdmby/nri/Ob87dv
37ztdDuJkJKv8V4ogpgX4olURRSoG1whn7I7HpeCJaVUbCkYZ3GkRMFjWLmKYlx2FSV5LF5lQOjm
buD3/T57cvTUzze86Mki6F1vyjQUxWg0Gk96zmT3N1CLoxSoDf/sdvK4XEdpZ6aKUnQ7QRYKFGAA
W/3nf+ebHOYOP8HtCS55+hPMGMGM3rNn7KwQXImQPd8xlw/27FkPZo1hVsph/5wHojFhsXC4Q4IT
mAr/HMI/pRQsz4JboRLgebEIsiThabhYnOkfOP3oEfOuBG6Hs4/3zBZ3IlWLxUUklUj1tOmeaTHM
i2Ea/oNzBv3PTMoCrqIspXmDPfPmMd/prQbDPbe1YXAa/vucS/FTB+ylCtBeZ/bb793OGlkF5wB7
oV6BxpzWX8J673IOhO9EIYEFuDPwj0JxB0PLMorDzmw0OAbbF5nKggwoDEZH3Q7PI5g5QqfyTi/m
r06nMH8dKRjsP/I/WFDw2zha4hr/2B/AQGmYu4jS8p6FPB76KGEh85inQvlgKTb0D/3R0Jscjfzh
0B/4Ij70748Pbw7H7GDAri7n7D341SUv2HDE+qPZaDIbTdm76zM27A8OmZ4Ke6HHzjpH/tDvvz3D
gY9gdhIKRjytAZhzk0nLEAzQRUwXVUBI1Or7rIjDn0tehI6OncGGguGKl2qTFbD0t85l+UGC5n43
Wv2tM0S1YqzU6h01L8fNy0nz8rB5edS8PG5eTpuXg9bGg0Hreti6bnE2GKMgIuXLWIAqVjyWkCtC
kYNypfZFma3UC3cg4ZhVHG0tFg3NxRlHw8zfXF2/f/P24gUMbcUSdIY63iiVy1mvB863KZfoIT2j
UDDQC3F3nWWxdGxSDTVdfjD0J02z1AHCrgVPHPv8Bd1+rS4sl4uFw6/Rw9X16dvrd/MvaaHmv1fR
AJX8EsXxWVamUCwcrbijrmL6/nRKvugo5nkMlF9lRfQxA9/fq5avF7xBfLFw+MI0yUPi77MOgUKe
xYIXF3y9dkSsx1qWb8t3ISBbhm9Wl2fz828tXsXEY6XZY1iXv14tFYh9mqroKufJvMgcwd3Rpuhj
EGjYFJ5vP/Ltj/V12nKx4MAm1PsEKs1i0eT5i/bWmAAWbNOGWzfHm8KP/HFT9H+KNOLxC55+a6Pf
E+GQpxa8GIb+ikdfRet0nhWqUcOdwbZPj9qGnU5jkaXBhqfrH2veatvpFOW3HC8Wl3j/r7u/I0jP
UQDo6JXgsdpcKa5KN+M3hj9Th88K/lGEmDALR0NUGvrfSTcua49TCMp5ydMdFUhXSmfQlXH4ML/x
OCrj3aOc4N8IatpksQA8vdsSW4+X7wx6mix5zt1Irsda5akp21WZi+IX2Pw7i1ex83iprvhKvAS9
O+FrRpqx22/b60rw9OZyv0DfzBP1JhCgmqe/4ozrKHh/3vBEPdI01Lgt1hfS7fdKR4a7toD7QBWK
N4/W65229jklHeUG3b67bWuOmmK/4LDo53L3rYvMHlYeb8T/5SkALW4WJqIp5b67zRzTrzomR9Lr
jTj9OB0ef0rSdt/xtZLvYQ9b+UI8RvLn5S4o+ErNLx2BncG2E7dqxrVYint2ESVAMfxUC/cde7ev
htlGwsWibhMWi0pufdDzCPWdhnc8DUT4S9TwmMawq8IJliOv1WnFZcCHx7lQ3yXH7Q3SWhMuq1+N
SSoJeg3JsZZlyZKri2y9bgDTxnDTx/p+C7n9gwe37NcsK8JNGcnPnxO0uvXhXzlF+GbO9QcwnFp+
6XgNZI1JVjpjcyX/oofNy0LMRZE00m411u5nBm3Yezh++bLfZ//BoJP4QwTqdbqK0kjtfmzRudFs
QLRZzp2fX+FvtFYfPvVqOqCt6ygR5hSz4W/N8RZArIV1u+AX/3xkOH6rPA47LhYNRr86HoGUR+1x
U+4KW57GomgkrMZw6zC0HY/nd1l8BTL8WBdyOYQoavL7hZMhUM52u/UFMI7kfXWLqqBuAcJCQVi0
Dy3tcNNTRv7EG391M3H8rXsL6ityzelj8Nzeo8KoWEUiDnv1ebpnjnV7qhCil3CpRNFraAWU91qJ
xDiW60eN4S/g+s+Ao++lOZe9x2OkK1GAIG/LWLiiuqMNN2lKeSvS3RpWFD9W0mpbaGlqRr86oVTk
enmS5JWHLONsaT3E1cef+HCAF7AA7lhO6b4P/gotqopQl52DeXXFzjIoTWuGD+8W6cH1pmRvAsWG
h2xwPBuMZ8Njdv7iGp9hHC1STcuL8pPxxB+NIUcNxoNqOM8KdTKcTA4nizTh98AtPj2SJ6NFSg+c
PLTgyWnKi2CzOzuHSZkKTxACEvqbsfk509Is0u0GdOLFkVQnWbpIeZpmJeAbQ9PjwSYCkgS6aYLE
oy3PBCU4xEkfFsVxtvVWcbTeAJXVys4C3J6ASZ11SbbUl6jrJAsFLl9lBWxYjRCBDS/CANxXX+V3
Oa0Ko9UqCspY7VBW/cxLZYUnhVJRupYnVgFSiLC6wCeUJy/OX56+u7hepNrbvA+lKHZE1AwUAQhD
u+EvP+dSQv4JT57RfyBkqTJP8jtBi+4isfVC0BqCwZNjq4NUqI0oaEYGXgRVO5IYNh5xcgImNHqN
QtgSnxpnpQJGlbhXUOa9HJAVXG5EHFPy0wwZQYUnVVEGOFErMUvx2a2nteboOEV/ddWe5oG+RG+h
p37eRpC1Fun9Mrv3MJ5hAj4Rq9Kkv0tidGGGIcUC8t6yoOeY5MQM7MYaTxkX4E8HDNpCKZg1CeOF
YKAUlqUQA2rDFQvQyeihdpQGcRmKEH6wB+GjqV1lCaxdIYk2VclXossy1LhEomxZCH7LdllZGGos
WjHQTgQVAPcAhyrAa6G0EOlfxbYi2AvFioNjSbbN0r8rxvNc8IKh0RMQOQDz7kAEYCOSWvrtRqSs
zNcFD4GAjyTxzxKc4QWDMIcaA9ZXYBEW83Rd8rVg+Gid1GcCWkZwHWewS/SRFKwXn21EYORpLgVG
bA4Tqb+NbqNchBH3s2Ldw6sePry+yVY3r6/e3ByOpt7wBteRSitSM7aA1LtedPRm7zfku0xlwFUa
MpCY4SN+1LYqeCpjep5Pt0m3xC/wAr+EIhOH4i4KBIMODLwbRxIireO73pbSPN2Rm1KFGfqsfhcC
WVqU/T4/Guv8xN4KCLECNWr5PMVAY5iwYJCZRM3uIs7+B0OaJlFw2yQ+Y/hygl58tYG1HJ1ZZsCi
2VbbkhtirJTgqVCEwFdI5NP5a5gJBS/UCqxvecDiMpPC3eKc0omlBapgmMcY+DW4DbK83DHjbLTA
pJ/qvqufg/cRWAHCfMd4GDKIe+2iyC445S2wxSWkA0zPDBxzKVA3YBHxoeQx2mod3cFc/SrJE7Mt
1JinRF7vCalPYEXxwNjYtM3gvt791zJZgg0g+k7lLg2uubyF8ChuId58PeOdBP2gI1txcd6myKCI
gNfAfNlllMiYyWHg211QSAIapMRICoLKjGNJmUb6PQlD/Yr8CuSCaCyyeygmSoAqQCyKibRiDzVs
WXq9wqDGSRi8XRapv4MOVUHrQoFli5y1tZo9ASnwvYuh1g1J4hlpQSU6urFEFTsT2z8DOAAtI0Jh
+ga4ZRIpzGaJWPPlTgFX7Epz06f9I4nWtrkBRNtGxB1pnmEJ0ZSsMSQpaBWBB0GCo1dTkM4Ksord
U3sDSFSSL68zECbD2EHV0U5rYtQj5masb1MVO6DMriBF8fD/gRiI/L4gBMKGf1MI6Lty4sOkuYov
Q08yiDhEByKsucJ9LWuD/nBccwede5RRgcOAlbhxQGndcFkF5QA2hLwUavejOR4WfRuOpiRkKeQ9
CGbQJSaTT6laqxjAXUzVAtOCnqapayoQpHXQ2wym93mDOQerJy3yHy5ARRjgDmrNRYBFVpKikGut
d722EgV0K3JZizzqG5nl00+wZTQwqjWw5sUS/MMLsjjWCFRH415Nk8MhS2YVM6sg1KFFKqmou9wA
7CnBT552bQp54CjGU3RKXq1sMklqH/TZG11H6Qq8ZZOVcVixEkHK2aasZl/7NsuJexD1sN+vpWUH
LylmHqRV8iNNoxJuVWSJzc96tZnhucmsZWkQyBj0oZvs8a7WasSTwaZMb6W1wiWHPF0mUKvwRIZZ
iIzyMY19dUTVW6EnGeompBiR9BBZlZB7xw6zLzJ9s21RLCUIzzQdPdn6kKZmJn5T8am0eQE0ScIq
wDiL3RRvOejgiyTxD5oINJWDIMGHYl1nl1xBR4bAhyPwhvIKjmeSG8Wsxsnmrs5oS1FVXKPgAzcP
2nuYM4qdQupd5g0cz9eVlbb2lGUH8tLk0Calup5To4OFNNR2RixJqAdXw6DhzGevoP8AtZ8AQAcP
P5u/68Ja4GIJ6WsbhWqjC4FJDNUGupOasaMKgNTgRJKKnMk+Ow0hBDc8XvWg/9CYKRTghmYz2Jbh
UQFa34lhBwE41BrI7PweIxaBF4+7Oh/g5u+jFAAtiAduJShKEVO8m6dzi0jqdgJBFy7a4htxSLTM
09wzA00kiH+hWJZr6xSZSb4MC1FB7i/uRVBqgIXZC9929Ku7Ev2EUFO+yf0ojZCdgZHTzrEx/J4X
KSZ/ZzX2WybdIyVDpMtCKEUoWD0z4RDRCZhZoVKLMsUuF8MfBEsoFQBlWzn0hiBv6kUrz4y6aBrQ
3H+xAaI4U50RwJMmLHgnyTAHG1CvexztJAMXkkvWk/QiRpf11oH1Kzoqcy2L/9OJama7sAwgPnqz
7Y+EhfiUzkKuOPSid7YLxN/V+QnedOTBd6AgNQiurK5BQH3sZSEU4VRwOSrgMhegcCzoaRbEUc5o
LbjXJWg54OhbSXZn8b8sBYY8hI7ErnmJr9phtxAFGzIgdt07cA3dY8dkp5gWV6bQxxiWpma1oR6X
Y7Ss1Nvo3ltq7WBLYrQjq42JFOrI4f0bsgyNnuLERCts7IFQqy0Xtglj5JdKH03QZJM2S2kaw0C/
ym56P1rk6UUzloP/3EWxaU0b4U1vMAlLklIPgSBQEaYahelm2DdgBcujxkLaT/CwCe8YAFQ7UOOG
hZy2YbvCnI+xsORSOFs+GUCe3bNXlw3hxmDfDaEC/6nJ+1K4vJigukbqeEhgDS2g1uk90Xe16uhw
pj61wXpC7Ttiem0+Hm/5Tmr6hlLLgLqSmjpS5z+jXoPSU7RH3EYdXTurcVy397TJdI+nCb6MSl0h
wRqsX1QqrZSoI2RWN9AQ4XhhMAo7eEuQxVlOXpUKfXCyFJrcUqyw5tHZHNZGtJimr/MHndk10A+Y
FpIK48h3hKdEAo8V8p05GTOYqMLcVIpWdGxtC3BVLldlTBMzqeKdhxkxCjSQoYOFAg+iFIlgRf4j
w85eA13JE0Fxr/MnwhsLAPdZDZVTWw2wIeNtBYMJAkImtQO1ddv/hHJ5AbRCOrihTAwqrpYbh9U6
HOmigCeeXplDThaNnBbgO7baBfFcqVF/XtCGJi9hNkJf0MUMYguKfcKMkMyeW1gISIuaKmAHHoTc
AVsXUDGbqqoPSGpt+Q/VZYrdlkd0/vWhFLoCg2/ZY+LQnoGVwpPgKjN2/JUU8ywv44qiuUIQ9oA4
/lESwUPvmal1ePrvkTejH+u2hpnj6Wp8UOU1rJszZvsf61xgm7TMZ2xat0U6QCj3WcxiD70BGPZN
WdAPH2CDiUUZuG01bEZ5sowgJu00/KMcq8/EZjav4jEe2GzD9LhGmsZ1bXQ9hC8Yex6evLbHqnLU
GgdcFaWrzHVOKEOePuyt524y9FJiyMfnVX6UVcynWbpLsIWm0JZgFOlIgacDZgKrJ5A0hGP4el2I
tTmnq85DsdHCj41uPy2qZglJSt95hgC9TEOtOvqMhzykAq6lZ8wcZGiAndtG0XjW0MnBGT4BoENo
EWc5QoQuVJd8w7swDKLhcbuq2xmAWCtRQMvpYY1IES7itAp2lmhXyC0OPWYegjpwtIQWTipdZmwq
N/S0VfUEu8dDI2px21aEDOugFYNAkTYusl0FGg0LG+5L0N6ssufEvrONudXex6r2C0jXFFmyrokA
nfBc4A17KKvcg1/fXJ/P8FGQHqUcia2/6UdNisQjbWjkQ+rFolVFCXp1kKfGjo12gQia0uC2zlAW
AalYnZ3fc0SK9hL7BuDVGHBmLWluQuLBY78Z+42wO2CULp0D/m5p6/pYg0f3URTJhCeVBT7FodMm
+2CSGrF9aIMgPUEhSf0najMBm0XAskGMDTHMzsTGjNVPdmmU4dPOGfNG0+l4fHR8ZBBDzcaMvbw4
vZ4NfzrqTqb3g+7oftQd/jT4KQSsp0vOE3wVIsDCcHLc19VJX40nBAI73Y64V4DsscXDdwTo1YLG
13Xoxs0REDaVMm4O5kF7ofyAX7aOWt/q6e8GnZFlANB60xzDB1BpiO+RN0bNJ7fuUFm0+FhFMX0h
1RhTrS8G12HrOmlN2EAG1i9/wMUf0rwJckiXyVI/PmtJCxA0pK8I3dGr+UVbTalqcZzsQFP0BaP5
xSZ+3x8M8cVc5uGLA5P+uH8EP//2GtxhOZoeTidjIZbDcBBORXg07Q+Xx0suhqOj5fD4aDUccBhn
fwPa8w0pcWheTqwT+A2BhFJF+I1dp28+NsgzGd23GDbnnfSBZfWF6VuxMqdzLS1skqylSkl7yj0y
R80xld2KFJBHy3jvofWDlE5cjuil7B2nB9hWqI9Rrr+dmfiDzp9//h9Hearq
===END CRASH DUMP===

**Comment by Thunder33345** [comment]
any like more "readable" logs?
Edit: Nevermind

**Comment by timbersquirrel** [comment]
thats what i though XD lemme see

**Comment by timbersquirrel** [comment]
its all fixed thanks dude!

**Comment by Thunder33345** [comment]
good
also try to be cautious as i didnt test the plugin
